### ISSUE TITLE
Could not open egl display

### ISSUE THREAD

**Issue by yhsilience** [rockchip-linux/carmachine#2]
我根据手册，编译rootfs，运行Carmachine .
./usr/bin/Carmachine -platform linuxfb 可以运行
./usr/bin/Carmachine -platform wayland 可以运行

export  export QT_GSTREAMER_WINDOW_VIDEOSINK=kmssink
./usr/bin/Carmachine -platform eglfs 无法运行

**Comment by wzyy2** [comment]
换yocto吧

**Comment by yhsilience** [comment]
我现在需要在linux下播放4k视频，用那种会比较好和容易？？？debain？？buildroot？？yocto？？

**Comment by yhsilience** [comment]
我使用firefly3399.。
